-- Extended species list - insert only if name_latin doesn't already exist
INSERT INTO species (name_he, name_en, name_latin, type, is_system)
SELECT v.name_he, v.name_en, v.name_latin, v.type, true
FROM (VALUES
('אזליאה סצוקי', 'Satsuki Azalea', 'Rhododendron indicum', 'temperate'),
('אלה אטלנטית', 'Atlantic Pistachio', 'Pistacia atlantica', 'temperate'),
('אלה ארצישראלית', 'Palestine Pistachio', 'Pistacia palaestina', 'temperate'),
('אלון התבור', 'Tabor Oak', 'Quercus ithaburensis', 'deciduous'),
('אלון מצוי', 'Kermes Oak', 'Quercus calliprinos', 'temperate'),
('אורן הגלעין', 'Stone Pine', 'Pinus pinea', 'conifer'),
('אורן הצנובר הסיני', 'Lacebark Pine', 'Pinus bungeana', 'conifer'),
('אורן הלבן היפני', 'Japanese White Pine', 'Pinus parviflora', 'conifer'),
('אורן השחור האירופי', 'European Black Pine', 'Pinus nigra', 'conifer'),
('אורן השחור היפני', 'Japanese Black Pine', 'Pinus thunbergii', 'conifer'),
('אורן ירושלמי', 'Aleppo Pine', 'Pinus halepensis', 'conifer'),
('אורן סקוטי', 'Scots Pine', 'Pinus sylvestris', 'conifer'),
('איקסורה', 'Ixora', 'Ixora coccinea', 'tropical'),
('אשחר רחב-עלים', 'Italian Buckthorn', 'Rhamnus alaternus', 'temperate'),
('בוגנוויליה', 'Bougainvillea', 'Bougainvillea glabra', 'tropical'),
('בוקיצה סינית', 'Chinese Elm', 'Ulmus parvifolia', 'deciduous'),
('גליציה תלת-קוצנית', 'Honey Locust', 'Gleditsia triacanthos', 'deciduous'),
('גינקגו דו-אונתי', 'Ginkgo', 'Ginkgo biloba', 'deciduous'),
('הדס מצוי', 'Common Myrtle', 'Myrtus communis', 'temperate'),
('הדס ננס', 'Dwarf Myrtle', 'Myrtus communis Compacta', 'temperate'),
('ויסטריה סינית', 'Chinese Wisteria', 'Wisteria sinensis', 'deciduous'),
('זית אירופי', 'European Olive', 'Olea europaea', 'temperate'),
('זית בר', 'Wild Olive', 'Olea europaea sylvestris', 'temperate'),
('זלקובה יפנית', 'Japanese Zelkova', 'Zelkova serrata', 'deciduous'),
('חרוב מצוי', 'Carob', 'Ceratonia siliqua', 'temperate'),
('לגרסטרמיה הודית', 'Crape Myrtle', 'Lagerstroemia indica', 'deciduous'),
('מייפל יפני', 'Japanese Maple', 'Acer palmatum', 'deciduous'),
('מייפל טרידנט', 'Trident Maple', 'Acer buergerianum', 'deciduous'),
('מיש דרומי', 'European Hackberry', 'Celtis australis', 'deciduous'),
('מיש סיני', 'Chinese Hackberry', 'Celtis sinensis', 'deciduous'),
('ספיון השעווה', 'Chinese Tallow', 'Triadica sebifera', 'deciduous'),
('סריסה', 'Tree of a Thousand Stars', 'Serissa foetida', 'tropical'),
('ערער אדום', 'Phoenician Juniper', 'Juniperus phoenicea', 'conifer'),
('ערער אופקי', 'Creeping Juniper', 'Juniperus horizontalis', 'conifer'),
('ערער זוחל', 'Japanese Garden Juniper', 'Juniperus procumbens', 'conifer'),
('ערער מצוי', 'Common Juniper', 'Juniperus communis', 'conifer'),
('ערער סאבין', 'Savin Juniper', 'Juniperus sabina', 'conifer'),
('ערער סיני איטוילגאווה', 'Itoigawa Juniper', 'Juniperus chinensis Itoigawa', 'conifer'),
('ערער סיני שימפאקו', 'Shimpaku Juniper', 'Juniperus chinensis Shimpaku', 'conifer'),
('ערער רם', 'Rocky Mountain Juniper', 'Juniperus scopulorum', 'conifer'),
('פיקוס בנימינה', 'Weeping Fig', 'Ficus benjamina', 'tropical'),
('פיקוס הגומי', 'Rubber Tree', 'Ficus elastica', 'tropical'),
('פיקוס דולב', 'Sacred Fig', 'Ficus religiosa', 'tropical'),
('פיקוס השדרות', 'Chinese Banyan', 'Ficus microcarpa', 'tropical'),
('פיקוס נריפוליה', 'Willow Leaf Fig', 'Ficus salicaria', 'tropical'),
('קוטונאסטר', 'Cotoneaster', 'Cotoneaster horizontalis', 'deciduous'),
('קרמונה', 'Fukien Tea', 'Carmona retusa', 'tropical'),
('רימון מצוי', 'Pomegranate', 'Punica granatum', 'tropical'),
('רימון ננס', 'Dwarf Pomegranate', 'Punica granatum Nana', 'tropical'),
('שזיף פיסרדי', 'Cherry Plum', 'Prunus cerasifera', 'deciduous'),
('תאנה', 'Common Fig', 'Ficus carica', 'deciduous'),
('תפוח בר', 'European Crab Apple', 'Malus sylvestris', 'deciduous')
) AS v(name_he, name_en, name_latin, type)
WHERE NOT EXISTS (
  SELECT 1 FROM species s WHERE s.name_latin = v.name_latin
);
